package DAO_challenge.model;

import DAO_challenge.util.DataTransferObject;


public class OrderItem implements DataTransferObject {
  private long id;
  //  The name of the sequence is autogenerated and is always tablename_columnname_seq, in your case the sequence will
  // be names names_id_seq.
  private final static String SEQUENCE = "orderitem_id_seq";
  protected String name;
  protected double price;
  protected long quantity;

  @Override
  public long getId() {
    return id;
  }

  public void setId(long id) { this.id = id; }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public double getPrice() {
    return price;
  }

  public void setPrice(double price) {
    this.price = price;
  }

  public long getQuantity() {
    return quantity;
  }

  public void setQuantity(long quantity) {
    this.quantity = quantity;
  }

}
