package DAO_challenge.model;

import DAO_challenge.util.DataTransferObject;


public class SalesPerson implements DataTransferObject {
  private long id;
  //  The name of the sequence is autogenerated and is always tablename_columnname_seq, in your case the sequence will
  // be names names_id_seq.
  private final static String SEQUENCE = "salesperson_id_seq";
  protected String name;

  @Override
  public long getId() {
    return id;
  }

  public void setId(long id) { this.id = id; }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }
}
